### ISSUE TITLE
Geneva's swap and swap-info

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/swap-fontside#36]
- [x] deploy swap to https://geneva-swap.moonchain.com/
- [x] deploy swap-info to https://geneva-swap-info.moonchain.com/

**Comment by hairyf** [comment]
related to https://github.com/MXCzkEVM/MEP-1759-DApp-store/issues/36 association

**Comment by SanghamitraBhowmick1993** [comment]
Could you confirm why we do not see any data in the tokens section?


![Image](https://github.com/MXCzkEVM/swap-fontside/assets/93600163/2c1ebdb4-1314-4e8d-bca0-731b47531c36)

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993 By https://github.com/MXCzkEVM/wannseeswap-tokenlist/blob/main/verify-stats.json The verifiedTokenList in is the displayed token list, and two have been added for testing

**Comment by hairyf** [comment]
If it is not displayed, please clear the cache

**Comment by SanghamitraBhowmick1993** [comment]
I attempted clearing the cache and also tried using a different browser, but I still couldn't view the token list.


![Image](https://github.com/MXCzkEVM/swap-fontside/assets/93600163/8e28ff3a-3539-43c5-911f-fcec36adcad3)

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993  Top Tokens only display data statistics for the current 24 hours

**Comment by SanghamitraBhowmick1993** [comment]
blocked due to https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=60679360

**Comment by SanghamitraBhowmick1993** [comment]
this is working
