### ISSUE TITLE
Swap DApps 'FROM' Textbox Does Not Clear Value When Tokens Are Switched

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/swap-fontside#37]
In the Swap DApps, the 'FROM' textbox fails to remove the entered value when switching between tokens, although the balance updates correctly. This issue results in confusion and potential errors during token swapping. The textbox should clear its value automatically when switching tokens to ensure a smooth user experience.

Steps to replicate is available here - 

https://github.com/MXCzkEVM/swap-fontside/assets/93600163/7cc5e230-43d9-45ce-a2d2-80d7326003ee

**Comment by hairyf** [comment]
Mainnet and testnet updated

**Comment by SanghamitraBhowmick1993** [comment]
This is working!! 

![Image](https://github.com/MXCzkEVM/swap-fontside/assets/93600163/e19eb144-11d8-49e4-bbca-0eec6811eeef)
